"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

upper_limit = 4_000_000
fibonacci_sequence = [1, 2]

while True:
    next_term = fibonacci_sequence[-2] + fibonacci_sequence[-1]
    if next_term >= upper_limit:
        break
    else:
        fibonacci_sequence.append(next_term)

sum = 0

for number in fibonacci_sequence:
    if number % 2 == 0:
        sum += number

print(sum)
